"""mapped_column_fix

Revision ID: 897fe5190785
Revises: 0cba59414206
Create Date: 2023-12-25 02:54:22.939460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '897fe5190785'
down_revision: Union[str, None] = '0cba59414206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('response', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticket', 'status',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('ticket', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ticket', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ticket', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ticket', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'status',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('response', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('response', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('response', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
