"""fix 9

Revision ID: b69f0acea392
Revises: 0c1f5beef4fd
Create Date: 2023-12-19 23:55:41.122080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69f0acea392'
down_revision: Union[str, None] = '0c1f5beef4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
